[theme]
primaryColor = "#0C7168"
backgroundColor = "#FAF8F3"
secondaryBackgroundColor = "#F0EEE7"
textColor = "#153C3A"
font = "sans serif"

[server]
maxUploadSize = 8

[browser]
gatherUsageStats = false
