[theme]
primaryColor = "#147D92"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EAF0F5"
textColor = "#172C42"
font = "sans serif"
[server]
headless = true
[browser]
gatherUsageStats = false
